name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7' ]

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Run RSpec
      run: bundle exec rspec
      env:
        BONGLOY_SECRET_KEY: ${{ secrets.BONGLOY_SECRET_KEY }}
