name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.x
    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run RSpec
      run: bundle exec rspec
      env:
        BONGLOY_SECRET_KEY: ${{ secrets.BONGLOY_SECRET_KEY }}
